export class User{
    constructor(
        public id: number,
        public name: string,
        public email: string,
        public emailTwo: string,
        public foto: string,
        public rol: string,
        public rolSecondary: string,
        public nickname: string,
        public position: string,
        public description: string,
        public userWhatsApp: string,
        public userTelegram: string,
        public mobile: string,
        public website: string,
        public aboutMe: string,
        public aboutPersonal: string,
        public aboutAcademy: string,
        public aboutProfessional: string,
        public location: string,
        public bgColor: string,
        public facebookLink: string,
        public twitterLink: string,
        public youtubeLink: string,
        public linkedinLink: string,
        public instagramLink: string,
        public githubLink: string,
        public emailVerifiedAt: Date,
        public password: string,
        public rememberToken: string,
        public createdAt: Date,
        public updatedAt: Date
    ){}
}